### ISSUE TITLE
JSON no Mocky.io

### ISSUE THREAD

**Issue by jeansanson** [jeansanson/Controle_robo#2]

**Comment by ricardoBpinheiro** [comment]
http://www.mocky.io/v2/5cf709a33200008a288cd582

JSON com os robos, responsaveis, categorias e localização.

**Comment by jeansanson** [comment]
SHA1: 37:CB:F1:1A:D0:31:EC:66:97:68:85:4D:E1:BB:48:7F:EF:BD:07:9E

**Comment by jeansanson** [comment]
https://medium.com/android-dev-br/sharedpreferences-d34768fcda45

**Comment by jeansanson** [comment]
http://www.corpshaala.com/wp-content/uploads/2018/09/robot-icon.gif
https://www.clipart.email/clipart/robot-clipart-gif-33170.html

**Comment by ricardoBpinheiro** [comment]
https://romannurik.github.io/AndroidAssetStudio/index.html
